### ISSUE TITLE
incorrect documentation for isChoices and isChoice

### ISSUE THREAD

**Issue by sbj42** [enquirer/prompt-choices#2]
The documentation for the `isChoices` and `isChoice` methods seem to be copy-pasted from `Separator`.  The example code blocks seem accurate, but the summary, params and return are wrong:

```js
/**
 * Create a new `Separator` object. See [choices-separator][] for more details.
 *
 * ```js
 * var Choices = require('prompt-choices');
 * var choices = new Choices(['foo']);
 * console.log(Choices.isChoices(choices)); //=> true
 * console.log(Choices.isChoices({})); //=> false
 * ```
 * @param {String} `separator` Optionally pass a string to use as the separator.
 * @return {Object} Returns a separator object.
 * @api public
 */
```

**Comment by jonschlinkert** [comment]
noted, thank you

**Comment by sbj42** [comment]
Not to nitpick, but 0041432 fixes the params but not the summaries which still say "Create a new `Separator` object."

**Comment by jonschlinkert** [comment]
Thanks for pointing that out.

**Comment by jonschlinkert** [comment]
not sure how I missed that btw, I could have sworn I read it over...
